project:
  type: book
  output-dir: _web
  
execute:
  eval: true
  echo: false
  output: false
  freeze: auto  # auto, true, or false

book:
  title: "Cambridge-area population forecasts"
  subtitle: ""
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - links.qmd
    - methodology.qmd
    - create_county_population_control_totals.qmd
    # - counties.qmd
    # - get-county-data.qmd
  # page-footer:
  #   center: "[Return to main MTA 2025 page](https://boyd-mta2025-links.netlify.app/)"      

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 4
    toc-expand: true

editor_options:
  chunk_output_type: console

# editor:
#   markdown:
#     wrap: 72
#     canonical: true
  
# use qstop shortcut for this
# ```{r stop_here, echo=FALSE}
# knitr::knit_exit()
# ```

# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 