---
editor_options: 
  chunk_output_type: console
editor:
  markdown:
    canonical: true  
---

# Births

Compare sources of births data.
Construct birth estimates.

## Setup
```{r}
#| label: setup

source(here::here("setup.R"))
```


```{r}
#| label: constants

mage_order <- c(
  "<15",
  "15-17",
  "18-19",
  "20-24",
  "25-29",
  "30-34",
  "35-39",
  "40-44",
  "45+",
  "Unknown",
  "Total"
)

```

## Get and smooth Census data on births

```{r}

df <- readRDS(fs::path(DWORK, "cocwide.rds"))
glimpse(df)


```

### Explore Census births data

The checks below show that Census calculates birth rates as births / (avg pop of current and prior year) * 1000.
For example, birth rate in 2018 = births in 2018 / avg pop of 2018 and 2017, x 1000.

```{r}
cnty <- "Westchester" # Albany Saratoga Washington Westchester
check <- df

check |>
  knitr::kable()

```


## Get NYSDOH births and fertility rates

```{r}

# births
fname <- "Vital_Statistics_Live_Births_by_Mother_s_Age_and_Resident_County__Beginning_2008_20250616.csv"
fpath <- fs::path(DNYG, fname)

df2 <- vroom::vroom(fpath)

```

```{r}

# fertility rates (and birth rates)
fname <- "Vital_Statistics_Live_Births_and_Fertility_Rates_by_Mother_s_Age_and_County__Beginning_2008_20250616.csv"


```

## Compare

```{r}

glimpse(df)
b1 <- df |>
  filter(stfips == "36", geotype == "county") |>
  select(stfips, cntyfips, shortname, year, pop, abirths)

b2 <- df2 |>
  select(year = Year, shortname = County, mage = 4, births = 5) |>
  filter(mage == "Total")

b12 <- b1 |>
  full_join(b2, by = join_by(shortname, year)) |>
  filter(!is.na(pop))

cnty <- "Warren" # Albany Washington
b12 |>
  filter(shortname == cnty) |>
  pivot_longer(cols = c(abirths, births)) |>
  filter(!is.na(value)) |>
  ggplot(aes(year, value, colour = name)) +
  geom_point() +
  geom_line() +
  ggtitle(cnty)

```
