---
editor_options: 
  chunk_output_type: console
editor:
  markdown:
    canonical: true  
---

# Get County Components of Change

https://www2.census.gov/programs-surveys/popest/datasets/


```{r}
#| label: setup

source(here::here("setup.R"))
```


## Census Components of Change

https://www.census.gov/programs-surveys/popest.html
https://www.census.gov/programs-surveys/popest/data/data-sets.html

https://www.census.gov/programs-surveys/international-programs/events/training/select-topics-in-international-population-health/demographic-change.html

### DON'T USE THIS YET -- 2010-2019

https://www.census.gov/data/tables/time-series/demo/popest/2010s-counties-total.html

```{r}
#| label: 2010-2019-coc
#| eval: false

# https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/cc-est2019-alldata.pdf

fname <- "co-est2019-alldata.csv"
fpath <- fs::path(dcenpop, fname)

# the rate variables must be per thousand I think

df <- vroom(fpath, col_types = cols(.default = col_character()))

tmp <- df |>
  rename_with(str_to_lower) |>
  filter(state == "36", county == "115")
tmp |>
  pivot_longer(cols = -c(sumlev:ctyname)) |>
  filter(str_detect(name, "2018"))

tmp |>
  pivot_longer(cols = -c(sumlev:ctyname)) |>
  filter(str_detect(name, "rdeath")) # rnatural rnetmig

vars <- c("rbirth", "rdeath", "rnetmig")
vars <- c("rbirth", "rdeath", "rinternationalmig", "rdomesticmig")
vars <- c(
  "rbirth",
  "rdeath",
  "rinternationalmig",
  "rdomesticmig",
  "rnaturalinc"
)


tmp |>
  pivot_longer(cols = -c(sumlev:ctyname)) |>
  mutate(
    year = str_sub(name, -4, -1) |> as.integer(),
    var = str_remove(name, as.character(year)),
    value = as.numeric(value),
    value = value / 1000,
    value = ifelse(var == "rdeath", -value, value)
  ) |>
  filter(var %in% vars) |>
  ggplot(aes(year, value, colour = var)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = 2010:2020) +
  scale_y_continuous(
    breaks = seq(-.01, .02, .002),
    labels = scales::label_percent()
  ) +
  ggtitle("Change in population by cause as % of starting (?) population")

```

### 2020-2024

https://www.census.gov/data/datasets/time-series/demo/popest/2020s-counties-total.html
https://www2.census.gov/programs-surveys/popest/tables/2020-2024/counties/totals/co-est2024-comp.xlsx
https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/counties/totals/co-est2024-alldata.csv

```{r}
#| label: 2020-2024-coc
#| eval: false

# url <- "https://www2.census.gov/programs-surveys/popest/tables/2020-2024/counties/totals/co-est2024-comp.xlsx"
url <- "https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/counties/totals/co-est2024-alldata.csv"
fname <- fs::path_file(url)
download.file(url, fs::path(dcenpop, fname), mode = "wb")

```
