"""Build `data_raw/MANIFEST.toml` — a reproducibility manifest.

For every file under `data_raw/` records:
- SHA-256 hash (for byte-exact provenance)
- size in bytes
- modification time (when the file landed in `data_raw/`)
- the URL it was downloaded from, if known (looked up from the
  `popfc.data.download.REGISTRY`)
- the DownloadSpec name, if registered

The manifest is committed to the repo so anyone can verify
data-provenance without depending on URLs staying alive.

Re-run after pulling fresh data:

    python scripts/build_manifest.py
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path

from popfc.data.download import REGISTRY
from popfc.paths import DATA_RAW, PROJECT_ROOT

MANIFEST_PATH = DATA_RAW / "MANIFEST.toml"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def url_lookup() -> dict[Path, tuple[str, str]]:
    """Build path -> (spec_name, source_url) from the download registry."""
    lookup: dict[Path, tuple[str, str]] = {}
    for name, spec in REGISTRY.items():
        if spec.source_url is None:
            continue
        # Resolve to an absolute path so the dict-lookup matches walked paths.
        lookup[spec.target.resolve()] = (name, spec.source_url)
    return lookup


def _toml_escape(s: str) -> str:
    """Escape a string for TOML basic-string syntax."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build() -> str:
    lines: list[str] = [
        '# Reproducibility manifest for popfc raw data.',
        '#',
        '# Generated by scripts/build_manifest.py. Re-run after refreshing',
        '# data via `python -m popfc.data.download` or by hand-placing files.',
        '#',
        '# Each entry records the file path (relative to project root), SHA-256,',
        '# size in bytes, on-disk mtime, and the source URL / download-spec name',
        '# when those are known.',
        '',
        f'generated_at = "{datetime.now(timezone.utc).isoformat()}"',
        '',
    ]

    url_map = url_lookup()

    # Walk data_raw/, skipping the manifest itself.
    files = sorted(
        p for p in DATA_RAW.rglob("*")
        if p.is_file() and p.name != MANIFEST_PATH.name
    )

    n_files = 0
    total_bytes = 0
    for fp in files:
        rel = fp.relative_to(PROJECT_ROOT).as_posix()
        size = fp.stat().st_size
        mtime = datetime.fromtimestamp(fp.stat().st_mtime, tz=timezone.utc).isoformat()
        digest = sha256_of(fp)
        spec_name, url = url_map.get(fp.resolve(), ("", ""))
        lines.append(f'[file."{_toml_escape(rel)}"]')
        lines.append(f'sha256 = "{digest}"')
        lines.append(f'size_bytes = {size}')
        lines.append(f'mtime = "{mtime}"')
        if spec_name:
            lines.append(f'download_spec = "{_toml_escape(spec_name)}"')
        if url:
            lines.append(f'source_url = "{_toml_escape(url)}"')
        lines.append("")
        n_files += 1
        total_bytes += size

    header_summary = [
        f'n_files = {n_files}',
        f'total_bytes = {total_bytes}',
        '',
    ]
    # Insert summary right after generated_at line.
    insert_idx = next(i for i, ln in enumerate(lines) if ln.startswith("generated_at"))
    for j, summary_line in enumerate(header_summary):
        lines.insert(insert_idx + 1 + j, summary_line)

    return "\n".join(lines) + "\n"


def main() -> None:
    toml = build()
    MANIFEST_PATH.write_text(toml, encoding="utf-8")
    print(f"wrote {MANIFEST_PATH.relative_to(PROJECT_ROOT)}: "
          f"{MANIFEST_PATH.stat().st_size:,} bytes")
    # Show a quick summary.
    n_files = sum(1 for ln in toml.splitlines() if ln.startswith("[file."))
    print(f"  files indexed: {n_files:,}")


if __name__ == "__main__":
    main()
